### ISSUE TITLE
Create simple freame integration witth Farcaster

### ISSUE THREAD

**Issue by gurobokum** [ZK-solidity-army/farcaster_lottery#1]
1. Frame with one button
2. Click on the button shows "Hello, World"
3. Launch on Farcaster

**Comment by kobadmitrii** [comment]
I use a very simple HTML 

`<!DOCTYPE html>
<html>
  <head>
    <title>My Farcaster Poll Frame</title>
    <meta property="fc:frame" content="vNext" />
  </head>
  <body>
    <meta property="fc:frame:image" content="https://cdn.glitch.global/b204e84b-90e9-43e8-b30d-474616e0a588/q?v=1714311439075" />
    <meta property="fc:frame:button:1" content="Hello, World" />
  </body>
</html>`

![Uploading Screenshot from 2024-04-28 16-46-07.png…]()

code, host it on https://glitch.com/ and make simple example: https://warpcast.com/x12/0xc4246c04

**Comment by kobadmitrii** [comment]
Also i used this link for tests: https://warpcast.com/~/developers/frames

**Comment by gurobokum** [comment]
Closed in https://github.com/ZK-solidity-army/farcaster_lottery/pull/20
